name: Makefile CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install re2c

    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Build mtag_stack
      run: |
        make

    - name: Run tests
      run: make test && ./test simple 2>&1 | tee /tmp/test_results.log

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: /tmp/test_results.log

    - name: Dist
      #if: startsWith(github.ref, 'refs/tags/v')
      run: |
        make dist
    - uses: actions/upload-artifact@v4
      with:
        name: release-tarball
        path: /tmp/dist/mtag_stack*.tar.gz

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        draft: false
        prerelease: false
        files: |
          /tmp/dist/mtag_stack*.tar.gz

#    - name: debug
#      if: ${{ failure() }}
#      uses: mxschmitt/action-tmate@v3

